### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by kristian94** [KIMB0/ufo-blog-entry#4]
Jeres abstract giver et godt overblik over problemstillingen. I kommer ind på hvad problemet er, hvorfor
det er et problem, og hvad man står til at opnå ved at løse det. Man kunne måske kondensere det en smule,
men det føles på den anden side grundigt og overbliksgivende som det er.

Eksempel på en sætning man kunne skrive kortere:

"This results in a far more stable system environment, 
and will ultimately result in better response times system-wide."

-->

"This results in a far more stable and responsive system environment"

... men det er som sagt en smagssag ;)

8

**Comment by Nordalf** [comment]
Rettet til og gjort mere kort og præcist.
