### ISSUE TITLE
Reliable Data from Credible Sources

### ISSUE THREAD

**Issue by kristian94** [KIMB0/ufo-blog-entry#5]
De fleste af jeres kilder virker pålidelige, men jeg ville måske personligt være lidt varsom med at bruge en ret gammel Hackernews post som kilde (selvom brugeren angiveligt var CTO hos 10gen). Jeg ville I stedet prøve at finde en lidt mere officiel artikel eller noget andet til at underbygge jeres blog. Kilderne
kunne godt være en smule bedre henvist i løbet af bloggen.

6

**Comment by Nordalf** [comment]
Jeg sletter den kilde, da den er 2224 dage gammel og ikke kan bruges længere. MongoDB er på version 3.6 nu og vi kan læse os frem til, at der er ikke er alle de problemer, som vi havde regnet med. Vi skal bare lære værktøjet bedre at kende 👍
