### ISSUE TITLE
Design Constraints and Assumptions

### ISSUE THREAD

**Issue by kristian94** [KIMB0/ufo-blog-entry#6]
Generelt forklarer i meget godt hvordan i har forbedret jeres performance ved at optimere CPU-intensive processer, og underbygger det med egne målinger. I skriver dog I jeres abstract at mongoDB er kendt for at være langsomt, når det skal bearbejde store mængder data, hvorimod i, i et senere afsnit, skriver at mongo er kendt for at være hurtigt. Jeg kan godt fornemme at det er to forskellige pointer i prøver at lave, men når man læser det første gang virker det umiddelbart lidt forvirrende. Man kunne også give bloggen lidt ekstra guf ved at sammenligne MongoDB med en SQL Database, for på den måde yderligere at underbygge jeres konklusioner (selvom dette måske er lidt uden for jeres scope).

7

**Comment by Nordalf** [comment]
Jeg har aflivet myten om, at MongoDB er hurtigere. NoSQL og SQL kan ikke sammenlignes på den måde. Derimod er der tilføjet en reference til til noget NoNSQL BASE vs SQL ACID, som er hvad deres holdning til data egentlig er. 
Tror dette giver en lidt bedre holdning til det hele.

https://github.com/KIMB0/ufo-blog-entry/pull/15
