### ISSUE TITLE
Theoretical Explanations

### ISSUE THREAD

**Issue by mawmaw1** [KIMB0/ufo-blog-entry#7]
Det virker til at i har en masse forskellige teorier når det kommer til MongoDB, men det er til tider svært at se hvordan i underbygger teorierne. Det er udbredt viden at MongoDB har svært ved at håndtere store mængder data påstår i, men det mangler noget underbyggelse i form af kilder.

Udover det, synes jeg i har fine forklaringer om jeres løsninger, mht indeksering og profiling, og hvilke løsninger der fixer hvilke problemer. 

I skriver at reparation og genstart af jeres databaseserver en gang i mellem, kan være en god løsning. Hvis i mener det, kunne det i så fald ikke tyde på, at der var flere problemer der skulle løses? Det kan vel ikke være meningen. Ellers kunne det være fint at smide en kilde ind her.

7

**Comment by Nordalf** [comment]
Jeg tænker, at det skal referere til, at det er sundt engang imellem at løsne op i processerne og dets oppe tid. Så det der menes er ift. [SLA'en](https://github.com/KIMB0/LSD_frontend/blob/master/Documents/SLA.md); "... ordinary maintenace windows once a month". 
Det er mere for at sikre, at tingene ikke har kørt i to år uden et genstart og man ikke kan forstå, at systemet kører dårligt. 
Der er dog ændret i teksten, så der skal genstartes i følge af en SLA.
https://github.com/KIMB0/ufo-blog-entry/pull/16
