### ISSUE TITLE
Design Criteria, Sample Calculations and Simulations

### ISSUE THREAD

**Issue by mawmaw1** [KIMB0/ufo-blog-entry#8]
I kommer fint ind på hvordan I fik løst problemerne i første omgang, med de forskellige værktøjer i har beskrevet. 
I skriver at i har mistet en masse data i forbindelse med nedbruddet, men i skriver ikke rigtig noget om hvordan i evt vil sikre jer mod en gentagelse. Er i begyndt at lave backups siden? Det står hverken i jeres blog eller jeres Post-Mortem analyse. Det tænker jeg er relevant, når i beskriver hvor slemt det helt generelt er at miste data.

5

**Comment by Nordalf** [comment]
https://github.com/KIMB0/ufo-blog-entry/pull/13 - Denne pull request retter "So now what?" afsnittet til, så der er kommet en tilføjelse med, at vi anbefaler folk at backup deres system, og at vores projekt er slut, så vi har ikke implementeret denne feature.
