### ISSUE TITLE
Previous work / future work

### ISSUE THREAD

**Issue by mawmaw1** [KIMB0/ufo-blog-entry#9]
I skriver at det ikke er så slemt at databasen bruger al hukommelse på den nye server i har flyttet den til, da det nu gav den oprindelige server et pusterum. Løste indekseringen også dette problem, eller er der stadig et problem med at jeres database bruger for meget hukommelse på den nye server? Det kunne være fedt at vide. Hvis det ikke er løst eventuelt også hvad i har af tanker omkring løsning af dette, som man kunne forestille sig vil give problemer henad vejen. 

Udover det, er det fint at i råder folk til at læse op på dokumentation, inden de giver sig i kast med et større projekt.

7

**Comment by Nordalf** [comment]
https://github.com/KIMB0/ufo-blog-entry/pull/14 - Vi har ændret vores Memory referencer til at være CPU power referencer, da det var det vi mente. 
Tak.
